-- 在 Supabase SQL Editor 執行一次，即可啟用跨裝置的「每日加油」功能。
-- visitor_id 是瀏覽器隨機產生的匿名 UUID，不保存姓名或其他個人資料。
create table if not exists public.team_cheers (
  id bigint generated by default as identity primary key,
  cheer_date date not null default (timezone('Asia/Taipei', now()))::date,
  visitor_id uuid not null,
  team text not null check (team in ('A', 'B', 'C')),
  created_at timestamptz not null default now()
);

-- 相容先前已建立、使用姓名欄位的版本。
alter table public.team_cheers add column if not exists visitor_id uuid;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'team_cheers'
      and column_name = 'advisor_name'
  ) then
    alter table public.team_cheers alter column advisor_name drop not null;
  end if;
end $$;

create index if not exists team_cheers_date_team_idx
  on public.team_cheers (cheer_date, team);

create unique index if not exists team_cheers_one_device_per_day_idx
  on public.team_cheers (cheer_date, visitor_id)
  where visitor_id is not null;

alter table public.team_cheers enable row level security;

drop policy if exists "anyone can read daily cheers" on public.team_cheers;
create policy "anyone can read daily cheers"
  on public.team_cheers for select
  to anon, authenticated
  using (true);

drop policy if exists "anyone can cheer today" on public.team_cheers;
create policy "anyone can cheer today"
  on public.team_cheers for insert
  to anon, authenticated
  with check (
    visitor_id is not null
    and cheer_date = (timezone('Asia/Taipei', now()))::date
  );

grant select, insert on public.team_cheers to anon, authenticated;
grant usage, select on sequence public.team_cheers_id_seq to anon, authenticated;
